### ISSUE TITLE
shaderc-rs update

### ISSUE THREAD

**Issue by btrepp** [mistodon/gfx-hal-tutorials#11]
Hi,

The package for the shader compilation says it's deprecated, I got tutorial 1 working using shaderc instead. Would you be interested in a pull request to update?

**Comment by mistodon** [comment]
Hi there! Yeah, I've seen a few people struggle with this - but honestly, I haven't even had time to check out shaderc yet. Any PR would be very welcome! But otherwise, I'll get around to it when I can.

**Comment by mistodon** [comment]
Tutorials have now all been updated to use shaderc!
