### ISSUE TITLE
Linux/Vulkan: Vulkan backend dependency needs "features" setting

### ISSUE THREAD

**Issue by crsaracco** [mistodon/gfx-hal-tutorials#7]
Hi, thanks for doing these tutorials! :)

I'm starting to run through these tutorials, and I got to the point in Part 1 where we [create graphics resources](https://www.falseidolfactory.com/2020/04/01/intro-to-gfx-hal-part-1-drawing-a-triangle.html#graphics-resources):

```rust
let (instance, surface, adapter) = {
    let instance = backend::Instance::create(APP_NAME, 1)
        .expect("Backend not supported");

    let surface = unsafe {
        instance
            .create_surface(&window)
            .expect("Failed to create surface for window")
    };

    let adapter = instance.enumerate_adapters().remove(0);

    (instance, surface, adapter)
};
```

I got the following error:

```
thread 'main' panicked at 'Failed to create surface for window:
UnsupportedWindowHandle', src/main.rs:50:13
```

(which corresponds to the `instance.create_surface().expect()` line).

I took a look at the Vulkan backend code, and realized that the `match` branches in `create_surface` are all guarded by `#[cfg(all(feature = "FOO", ...))]`

I saw my system was trying to use the `Xlib` window handle, so I threw in `features = ["x11"]` to my Vulkan backend dependencies in `Cargo.toml`:

```
[target.'cfg(all(unix, not(target_os = "macos")))'.dependencies.backend]
package = "gfx-backend-vulkan"
features = ["x11"]
version = "=0.5.1"
```

And it started working again. However, this is *probably* not the way to solve it for all Vulkan users :) I'm not sure what the correct way to solve this is, so I'm leaving this issue here instead.

**Comment by raum-dellamorte** [comment]
I am having the same issue with the failure at `create_surface()`.  I got super hopeful when I saw the solution of adding `features = ["x11"]` but it won't even try to compile with that.

```
error: failed to run custom build command for `x11 v2.18.2`

Caused by:
  process didn't exit successfully: `.../gfx-hal-tut/target/release/build/x11-b8de83c57daad149/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Failure {
 command: "\"pkg-config\" \"--libs\" \"--cflags\" \"x11\" \"x11 >= 1.4.99.1\"",
 output: Output { status: ExitStatus(ExitStatus(256)), stdout: "",
 stderr: "Package x11 was not found in the pkg-config search path.\n
Perhaps you should add the directory containing `x11.pc\'\n
to the PKG_CONFIG_PATH environment variable\n
No package \'x11\' found\n
Package x11 was not found in the pkg-config search path.\n
Perhaps you should add the directory containing `x11.pc\'\n
to the PKG_CONFIG_PATH environment variable\n
No package \'x11\' found\n
" } }', /home/raum/.cargo/registry/src/github.com-1ecc6299db9ec823/x11-2.18.2/build.rs:36:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I tried changing it to "wayland" but that's not a valid option.  So, yes, that's not a fix-all, but there must be a solution.  I'm stumbling in a different project to use GL directly in rust, because I couldn't make sense of gfx-hal or glium, but I have hope that I'm going to get comfortable with gfx-hal.  I just have get a blasted triangle on the screen.

**Comment by torresguilherme** [comment]
@raum-dellamorte you need the x11 development libraries. this pkg-config command is trying to find their flags to use in the compilation

**Comment by raum-dellamorte** [comment]
> @raum-dellamorte you need the x11 development libraries.

Thanks, @torresguilherme, I was up past bedtime and I was sure it was just some change to the cargo.toml that would make it work and I couldn't figure it out.

Hazzah!  So for Linux, after a quick `sudo apt install libx11-dev`, @crsaracco's fix worked perfectly.
```
[target.'cfg(all(unix, not(target_os = "macos")))'.dependencies.backend]
package = "gfx-backend-vulkan"
features = ["x11"]
version = "=0.5.1"
```
I have a triangle!

**Comment by mistodon** [comment]
Glad to see this fixes it :0

I'm not sure what the best way is to handle Linux features - I guess ideally I'd want a way to auto-detect the window manager? Idk, I haven't really dug into it.

I'm going to close this issue for now - but please feel free to reopen if you think changes need to be made.
