### ISSUE TITLE
failed to run custom build command for `glsl-to-spirv v0.1.7`

### ISSUE THREAD

**Issue by GenuineJakob** [mistodon/gfx-hal-tutorials#9]
Hi, I am trying to learn with your tutorial, but I can't compile it.
` failed to run custom build command for `glsl-to-spirv `v0.1.7`

I think this dependency got replaced with [shaderc](https://github.com/google/shaderc).
Could you please look at this error, and if it isn't a lot of work change the dependency?

**Comment by torresguilherme** [comment]
it's not too much work. you can see how to compile it in the [shaderc-rs docs example](https://docs.rs/shaderc/0.6.2/shaderc/#examples)
